spring:
  datasource:
    url: jdbc:mysql://carbon-nono.cdspom5j0apx.ap-northeast-2.rds.amazonaws.com:3306/CARBON_NONO
    username: admin
    password: adminadmin

  jpa:
    hibernate:
      ddl-auto: update # 운영시에는 validate 추천
    show-sql: true